### ISSUE TITLE
cli not working after updating emebr to 1.9.0 version 

### ISSUE THREAD

**Issue by zion03** [ember-cli/ember-cli#2849]
Errors in different versions ember cli:

`version: 0.0.36`
The `TemplateCompiler` addon must implement the `included` hook.Error: The `TemplateCompiler` addon must implement the `included` hook.

`version: 0.0.37`
object is not a functionTypeError: object is not a function

`version: 0.0.47`
Path or pattern "vendor/loader.js/loader.js" did not match any files [string exception]

afetr update bower.json --> `"loader.js": "stefanpenner/loader.js#1.0.1"`, I got:
 ENOENT, no such file or directory '/application/ember/chat/tmp/tree_merger-tmp_dest_dir-5fRtNb2e.tmp/ember-data.js'

bower.json deps:

```
"dependencies": {
"jquery": "1.11.1",
"qunit": "~1.12.0",
"ember-qunit": "~0.1.5",
"ember": "1.9.0",
"ember-resolver": "~0.1.1",
"loader.js": "stefanpenner/loader.js#1.0.1",
"ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.2",
"ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
"ember-qunit-notifications": "^0.0.1",
"ember-cli-test-loader": "rjackson/ember-cli-test-loader#0.0.2",
 }
```

package.json

```
"devDependencies": {
 "body-parser": "^1.2.0",
 "ember-cli": "0.1.2",
 "ember-cli-ember-data": "0.0.4",
 "ember-cli-htmlbars": "^0.6.0",
 "ember-cli-ic-ajax": "0.0.3",
 "express": "^4.1.1",
 "glob": "^3.2.9",
 "originate": "0.1.5"
 }
```
