### ISSUE TITLE
Addon :: Getting Uncaught TypeError: undefined is not a function after upgrade to 0.2.2

### ISSUE THREAD

**Issue by alvincrespo** [ember-cli/ember-cli#3758]
I get this error when trying to open up Ember Inspector, but I'm not sure whether this is a project setup issue, ember-cli issue or ember-inspector. At the moment its kind of tough to pinpoint how to lookup where the entry of error is happening.

**Debugger w/ Pause on Exceptions on**

![](http://cl.ly/image/0L1O3M3b2H2e/Screen%20Shot%202015-04-02%20at%2010.53.43%20AM.png)

**Environment Info**

Using Ember Inspector 1.7.2

```
➜  fly-components git:(master) ember version
version: 0.2.2
node: 0.12.0
npm: 2.7.4
```

**bower.json**

```
➜  fly-components git:(master) cat bower.json
{
  "name": "fly-components",
  "dependencies": {
    "jquery": "^1.11.1",
    "ember": "1.11.0",
    "ember-data": "1.0.0-beta.16.1",
    "ember-resolver": "~0.1.15",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.3.0",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "~1.17.1",
    "fly-css-framework": "git@github.com:customerio/fly-css-framework.git"
  }
}
```

**package.json**

```
➜  fly-components git:(master) cat package.json
{
  "name": "fly-components",
  "version": "0.0.0",
  "description": "The default blueprint for ember-cli addons.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.2",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-disable-prototype-extensions": "^1.0.0"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^4.0.0",
    "ember-cli-htmlbars": "^0.7.4"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by alvincrespo** [comment]
So this looks like an error in our addon. We disabled `ember-disable-prototype-extensions` and things started working again, so now its about running through the code and seeing whats up. Is there a better way to debug this?

**Comment by rwjblue** [comment]
* Addons in `0.2.2` will disable prototype extensions by default
* ember-inspector had a bug where it was depending on prototype extensions which was fixed in https://github.com/emberjs/ember-inspector/pull/316
* @teddyzeenny is planning to release a new version this weekend with the fix

**Comment by alvincrespo** [comment]
@rwjblue Thanks for the bullet points! I'm going to remove ember-disable-prototype-extensions for now so I can use the inspector and then add it back in once the fix is up for ember-inspector.

**Comment by stefanpenner** [comment]
@teddyzeenny lets us know when the fix is released.

Also, we may want the inspector to run with this add-on as-well.

**Comment by teddyzeenny** [comment]
1.7.3  was published today but is waiting for a manual review on the Chrome Webstore for some reason, and may take "several business days" to be approved.
As for Firefox it's still stuck on 1.6.4 and has been in review for 2 months now.

The best way to use the inspector now with the [new bug fixes](https://github.com/emberjs/ember-inspector/blob/44837fe0ffd6a7081443406bd8d5fdbfce89733e/CHANGELOG.md#ember-inspector-173) is to use the [bookmarklet](https://github.com/emberjs/ember-inspector#bookmarklet-all-browsers).

@stefanpenner re: inspector running with prototype extensions disabled. This is directly related to https://github.com/emberjs/ember-inspector/issues/339

**Comment by teddyzeenny** [comment]
New version is out (on Chrome webstore). This can be closed.

**Comment by rwjblue** [comment]
Awesome, thanks for confirming Teddy!
