### ISSUE TITLE
Cannot find module 'chalk' on build with 0.1.12

### ISSUE THREAD

**Issue by funtusov** [ember-cli/ember-cli#3179]
Sorry, I don't have much details, that's from a deployment server to which I don't have access. Posting it here because switching the version from 0.1.12 to 0.1.9 makes it work, maybe that would be helpful for someone. I'll try to investigate the reason later.

```
$> npm cache clean
$> npm install
$> ember build
version: 0.1.12
Cannot find module 'chalk'
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/app_name/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by abuiles** [comment]
Seems something related with your env? can you run `rm -rf node_modules && npm cache clear && npm i` once more and see if it still persists?

**Comment by abuiles** [comment]
I think this is something related with you env, I'll reopen if we see more people reporting this.
