### ISSUE TITLE
error running blueprints after upgrade from 2.8 to 2.12

### ISSUE THREAD

**Issue by santo74** [ember-cli/ember-cli#7030]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.12.3
http_parser: 2.7.0
node: 4.8.2
v8: 4.5.103.46
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2k
os: linux x64
2.15.11
0.10
```

After upgrading from ember/ember-cli 2.8 to ember/ember-cli 2.12 (via incremental upgrades) I can't run any blueprints anymore.
E.g. when I run
```
ember g component testcomponent
```
I get the following error:
```
Error: Cannot find module 'ember-cli-is-package-missing'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/santo/devel/test/node_modules/ember-source/blueprints/component-test/index.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.CoreObject.extend._process.afterHook._locals.then.generateFileMap.fileMapVariables.processFiles.templateVariables._locals.Blueprint.load (/home/santo/devel/test/node_modules/ember-cli/lib/models/blueprint.js:1274:31)
    at Function.CoreObject.extend._process.afterHook._locals.then.generateFileMap.fileMapVariables.processFiles.templateVariables._locals.Blueprint.lookup (/home/santo/devel/test/node_modules/ember-cli/lib/models/blueprint.js:1251:24)
    at GenerateTask.lookupBlueprint (/home/santo/devel/test/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:93:22)
    at GenerateTask.run (/home/santo/devel/test/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:22:30)
    at Class.run (/home/santo/devel/test/node_modules/ember-cli/lib/commands/generate.js:64:17)
    at /home/santo/devel/test/node_modules/ember-cli/lib/models/command.js:238:20
    at initializePromise (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1077:33)
    at Class.validateAndRun (/home/santo/devel/test/node_modules/ember-cli/lib/models/command.js:194:12)
    at /home/santo/devel/test/node_modules/ember-cli/lib/cli/cli.js:163:24
    at tryCatch (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/home/santo/devel/test/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2414:5)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

I followed the regular upgrade approach as usual:
```
npm uninstall -g ember-cli
npm cache clean && bower cache clean
npm install -g ember-cli@2.12.3

rm -rf node_modules bower_components dist tmp
npm install --save-dev ember-cli@2.12.3
bower install
ember init
```

My application is running fine, but running an ember-cli blueprint gives the above error.
Any ideas what could be wrong?

**Comment by santo74** [comment]
Never mind, there was something wrong with my npm installation.
While I had npm v4.5 installed, ember still used an older version which isn't compatible with the latest ember versions.
