### ISSUE TITLE
Uncaught TypeError: undefined is not a function after update from 0.40 to 0.44

### ISSUE THREAD

**Issue by NedgoIO** [ember-cli/ember-cli#1950]
My little test project served up just fine with version 0.40, but now I get "Uncaught TypeError: undefined is not a function" when I needed to upgrade in order to use ember-cli-bootstrap

the file/line in question that it doesn't like is initializers/auth.js:7, which is just `init: function() {`

I upgraded the app with `npm install --save-dev ember-cli` and then ran `ember init`

The darn thing won't let me rollback the version of ember-cli with npm either...

here are my files for this simple project:
#### index.html

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EmberFireLogin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{BASE_TAG}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/ember-fire-login.css">
  </head>
  <body>
    <script>
      window.EmberFireLoginENV = {{ENV}};
      window.EmberENV = window.EmberFireLoginENV.EmberENV;
    </script>
    <script src="assets/vendor.js"></script>
    <script src="assets/ember-fire-login.js"></script>
    <script>
      window.EmberFireLogin = require('ember-fire-login/app')['default'].create(EmberFireLoginENV.APP);
    </script>
  </body>
</html>
```
#### templates/application.emblem

```
h2#title Welcome to Ember.js

== outlet
```
#### templates/index.emblem

```
if auth.authed
    h4 Congratulations! You are logged in!
    h4 Would you like to logout?
    button{action 'logout' this} Logout
else
    h4 Please login
    button{action 'login' this} Login
```
#### app.js

```
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';

Ember.MODEL_FACTORY_INJECTIONS = true;

var App = Ember.Application.extend({
  modulePrefix: 'ember-fire-login', // TODO: loaded via config
  Resolver: Resolver
});

loadInitializers(App, 'ember-fire-login');

export default App;
```
#### router.js

```
import Ember from 'ember';

var Router = Ember.Router.extend({
  location: EmberFireLoginENV.locationType
});

Router.map(function() {
});

export default Router;
```
#### index.js

```
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    login: function() {
        this.get('auth').login();
    },

    logout: function() {
      this.get('auth').logout();
    }
  }
});
```
#### initializers/auth.js

```
import Ember from 'ember';

var Ref = new window.Firebase("https://******.firebaseio.com/");

var auth = Ember.Object.extend({
  authed: false,
  init: function() {
    this.authClient = new window.FirebaseSimpleLogin(Ref, function(error, twitterUser) {
      if (error) {
        alert('Authentication failed: ' + error);
      } else if (twitterUser) {
        this.set('authed', true);
      } else {
        this.set('authed', false);
      }
    }.bind(this));
  },

  login: function() {
    this.authClient.login('twitter');
  },

  logout: function() {
    this.authClient.logout();
  }
});


export default {
  name: 'Auth',

  initialize: function( container, app ) {
        app.register('auth:main', auth, {singleton: true});
        app.inject('controller', 'auth', 'auth:main');
        app.inject('route', 'auth', 'auth:main');

  }

};
```
#### adapters/application.js

```
import DS from 'ember-data';

export default DS.FirebaseAdapter.extend({
  firebase: new window.Firebase('https://******.firebaseio.com')
});
```
