### ISSUE TITLE
pushObject is not a function in addon component

### ISSUE THREAD

**Issue by smartlaksh** [ember-cli/ember-cli#3839]
pushObject is not a function in addon component js

**Comment by stefanpenner** [comment]
this isn't actionable, can you please provide some information?

* what where you doing
* what happened
* what should have happened
* what version of ember-cli / ember / node / npm / os

**Comment by smartlaksh** [comment]
Hi @stefanpenner  I'm trying to pushObjects to the existing array/list.
export default Ember.Component.extend({
	seriesList: [],
	classNames: ['chart'],
	charts: null,	
	init: function() {
		this.initializeSeries();
	},
	initializeSeries: function(){
		var data = this.sampleJson();
	        var Series1 = {name: "GOOG", data: data};
	        var Series3 = {name: "IBM", data: data};
	        this.get('seriesList').pushObjects([Series1,Series3]);
	},
});

but it throws an exception pushObject is not a function.

the same code works fine with ember-cli@0.1.15 but not with 0.2.3

**Comment by smartlaksh** [comment]
OS: windows 
Ember-cli version: 0.2.3
node: 0.12.0
npm: 2.7.6

**Comment by stefanpenner** [comment]
@smartlaksh can i assume this is in an add-on ?

**Comment by smartlaksh** [comment]
yes it's an addon.

**Comment by stefanpenner** [comment]
`Ember.EXTEND_PROTOYPES `  is disabled in add-ons as not to force that mode onto all users.

**Comment by stefanpenner** [comment]
this is part of the `0.2.2` release notes: https://github.com/ember-cli/ember-cli/releases/tag/v0.2.2

**Comment by smartlaksh** [comment]
@stefanpenner FYI I have var on = Ember.on; in the same component

**Comment by stefanpenner** [comment]
> @stefanpenner FYI I have var on = Ember.on; in the same component

`pushObject` is also an extension

**Comment by stefanpenner** [comment]
hopefully that helps

**Comment by smartlaksh** [comment]
Got it @stefanpenner thanks
