### ISSUE TITLE
upgraded to 1.4, now my model hooks break

### ISSUE THREAD

**Issue by mgenev** [ember-cli/ember-cli#2763]
I opened this at the ember-cli repo, because others say they have the same issue after upgrading to 1.4. My other versions are 1.10 ember beta with htmlbars and handlebars 2

I have post model and a router set up like this:

```
this.resource('posts', function() {
        this.route('post', {
            path: ':post_id'
        });

        this.route('create', {
            path: 'create'
        });
    });
```

When I hit either posts, or posts/create, it works without a model hook and renders the template, but if there is a model hook with a this.store.find('post') or a this.createRecord('post'), it gives me these errors

```
 Error while processing route: posts.create undefined is not a function TypeError: undefined is not a function
```

or 

```
Error while processing route: posts.index Cannot read property 'ajax' of undefined TypeError: Cannot read property 'ajax' of undefined
```
