### ISSUE TITLE
Cannot find module 'broccoli-sourcemap-concat'

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-cli/ember-cli#5277]
after upgrading from ember-cli 1.13.x to 2.2.0-beta.2
```
version: 2.2.0-beta.2-v2.2.0-beta.2-c78d55f84b
Cannot find module 'broccoli-sourcemap-concat'
```

**Comment by rwjblue** [comment]
What is the rest of the stack trace?

**Comment by ballPointPenguin** [comment]
```
Cannot find module 'broccoli--concat'
Error: Cannot find module 'broccoli--concat'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Class.Addon.concatFiles (/home/brosas/forks/ember-cli/lib/models/addon.js:184:10)
    at Class.module.exports.postprocessTree (/home/brosas/codex/fire-drake/node_modules/ember-cli-blanket/index.js:82:28)
    at /home/brosas/forks/ember-cli/lib/broccoli/ember-app.js:493:27
    at Array.forEach (native)
    at EmberApp.addonPostprocessTree (/home/brosas/forks/ember-cli/lib/broccoli/ember-app.js:491:23)
    at EmberApp.toTree (/home/brosas/forks/ember-cli/lib/broccoli/ember-app.js:1508:15)
```

**Comment by ballPointPenguin** [comment]
I think I have a working PR.

**Comment by rwjblue** [comment]
Looks like https://github.com/ember-cli/ember-cli/pull/5221 forgot to fix https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L173-L185. My guess is that some addon you are using is utilizing `this.concatFiles`.

A short term work around would be `npm install --save-dev broccoli-sourcemap-concat`.

**Comment by rwjblue** [comment]
@ballPointPenguin - PR sounds great.  Ultimately, updating those references from `broccoli-sourcemap-concat` to `broccoli-concat` should fix things for you, but we also need to ensure that this function gets under test...

**Comment by stefanpenner** [comment]
This.concatFiles should be deprecated and removed

**Comment by ballPointPenguin** [comment]
closing in favor of #5280
