### ISSUE TITLE
ember test fails on PhantomJS after upgrading to 2.13: undefined is not a function

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#7042]
After upgrading to ember-cli to 2.13.1, `ember test` started failing for several unit tests, emitting errors like `undefined is not a function (evaluating 's.startsWith(prefix)')`. I'm not sure why this happens -- those tests run fine on PhantomJS when I ran them before the upgrade.

See https://travis-ci.org/getslash/backslash/builds/232516703#L6205 for the full output

If any more details are needed I'll gladly provide them. Thanks in advance!

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
0.23.3
```

**Comment by stefanpenner** [comment]
Interesting, I'm curious where `startsWith` is being called. As that is ES6 only, and would require a polyfill in phantom.

**Comment by stefanpenner** [comment]
https://github.com/getslash/backslash/blob/develop/webapp/ember-cli-build.js#L20 does clearly claim to include the polyfil.

**Comment by vmalloc** [comment]
@stefanpenner It's on a side branch. Perhaps this fix I made to bypass mirage's issues with polyfill is to blame? https://github.com/getslash/backslash/blob/fd4482f2795d12a11dfe24a5b26af0c01ade808b/webapp/ember-cli-build.js#L24

**Comment by stefanpenner** [comment]
I believe the syntax for including the polyfill is different: https://github.com/babel/ember-cli-babel#polyfill then what you have here: https://github.com/getslash/backslash/blob/develop/webapp/ember-cli-build.js#L20

**Comment by stefanpenner** [comment]
lets see if that makes CI happy: https://github.com/getslash/backslash/pull/214

**Comment by vmalloc** [comment]
@stefanpenner it's on a side branch - feature/ember-cli-upgrade

**Comment by vmalloc** [comment]
`develop` is still 2.10

**Comment by stefanpenner** [comment]
@vmalloc thanks, looks like you have it explicitly disabled in tests: https://github.com/getslash/backslash/pull/214/files#diff-a62a868db91bf557ba81a9d11950f75cL24

Without the polyfil enabled in tests you wont be able to use `String.prototype.startsWith` in phantom.

**Comment by vmalloc** [comment]
@stefanpenner Yes, that was following an advice from another thread (https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2Fsamselikoff%2Fember-cli-mirage%2Fissues%2F1084) When it was set to `true`, I had other strange issues (like this one https://travis-ci.org/getslash/backslash/builds/232506426#L6052)

**Comment by stefanpenner** [comment]
You will need to set it to true to use the es6 polyfill features.

It looks like the fix to issue you ran into was merged.

But i suspect we should squash the root cause: https://github.com/ember-cli/loader.js/issues/114

@rwjblue am I write in blaming ^ as the root cause?

**Comment by vmalloc** [comment]
@stefanpenner Ok, will subscribe to the relevant issues. Thanks a lot for taking the time to help! Much appreciated.

**Comment by rwjblue** [comment]
`at global code (http://localhost:7357/assets/tests.js:2095:8): Object is not a function (evaluating '(0, _lodash_defineProperty['default'])')` shows this is a duplicate of #7001.  The fixes in mike-north/ember-lodash#104 and mike-north/ember-lodash#105 address. 

> @rwjblue am I write in blaming ^ as the root cause?

Yes
