### ISSUE TITLE
ENOENT, open '/package.json'

### ISSUE THREAD

**Issue by adamsrog** [ember-cli/ember-cli#3776]
Getting an error occasionally when creating a new project, but it doesn't occur every time. 

    ~/Workspace/rog
    ember new test-project
    version: 0.2.2
    0.2.2

    installing
      create .bowerrc
      create .editorconfig
      create .ember-cli
      create .jshintrc
      create .travis.yml
      create Brocfile.js
      create README.md
      create app/app.js
      create app/components/.gitkeep
      create app/controllers/.gitkeep
      create app/helpers/.gitkeep
      create app/index.html
      create app/models/.gitkeep
      create app/router.js
      create app/routes/.gitkeep
      create app/styles/app.css
      create app/templates/application.hbs
      create app/templates/components/.gitkeep
      create app/views/.gitkeep
      create bower.json
      create config/environment.js
      create .gitignore
      create package.json
      create public/crossdomain.xml
      create public/robots.txt
      create testem.json
      create tests/.jshintrc
      create tests/helpers/resolver.js
      create tests/helpers/start-app.js
      create tests/index.html
      create tests/test-helper.js
      create tests/unit/.gitkeep
      create vendor/.gitkeep
    ENOENT, open '/Users/adamsrog/Workspace/rog/package.json'

Notice the `package.json` is trying to load from the directory I ran `ember new` in (`/Users/adamsrog/Workspace/rog/package.json` - doesn't exist), not the new project's dir (`/Users/adamsrog/Workspace/rog/test-project/package.json`).  I'm not sure if that is related, but I thought it was worth mentioning.  

Another observation is the version number is printed out twice (see above).  When the `ember new` command is successful, that extra version printout isn't present.

In any case, I `rm -rf test-project` and run `ember new test-project` again and it works fine.

Not sure what is causing this behavior so I figured I'd open an issue about it.  Has anyone else experienced this?

    ember version
    version: 0.2.2
    node: 0.12.0
    npm: 2.7.4

**Comment by stefanpenner** [comment]
maybe we have a small race between writing to disk and us expecting the file to exist...

**Comment by kellyselden** [comment]
looks to be related #3720

**Comment by adamsrog** [comment]
Could it be possible that in [/tasks/create-and-step-into-directory.js#L41](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/create-and-step-into-directory.js#L41): `process.chdir(directoryName);` is possibly failing - hence trying to use the incorrect `package.json`?  Just a thought.

**Comment by stefanpenner** [comment]
> process.chdir(directoryName); is possibly failing - hence trying to use the incorrect package.json?

ya, maybe we need to assert there, to catch issues sooner...

**Comment by adamsrog** [comment]
I'll check it out and see if I can reproduce the problem again, hopefully with more info.

**Comment by trek** [comment]
@stefanpenner I got a report of this happening again on `ember new`. Running `ember new` later did not reproduce. I think we are indeed running into an npm race condition.

**Comment by sidewinder** [comment]
I could reproduce this on a windows 8.1 with node 0.12.0. with first time running then second time it does not happen anymore.

**Comment by cwarny** [comment]
Just happened to me too on a Mac OSX Yosemite 10.10.2, node 0.12.0, npm 2.5.1, ember-cli 0.2.2

**Comment by stefanpenner** [comment]
> Just happened to me too on a Mac OSX Yosemite 10.10.2, node 0.12.0, npm 2.5.1, ember-cli 0.2.2

consistently or intermittently ?

**Comment by cwarny** [comment]
Intermittently. I just tried again and it went fine

**Comment by adamsrog** [comment]
Seems like it is occuring when people use `ember new` for the first time since upgrading their `ember-cli` version (0.2.2 in this case).  I've not been able to reproduce it again since my initial post.  I'm on Mac OS X 10.10.2 as well.

**Comment by visualjeff** [comment]
Happened with 0.2.3

$ ember -v
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 1.6.3
npm: 2.7.6

**Comment by stefanpenner** [comment]
i think there is a race with `process.chdir` in node, although it claims to be sync. I believe it may not always, this may be the cause of this..

**Comment by unchris** [comment]
I just had this happen to me. I was following the instructions at http://www.ember-cli.com/ exactly and as soon as I hit `ember new` I got the ENOENT error as described above.

```bash
⇒  ember -v
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```
Yosemite 10.10.2

**Comment by reflections55** [comment]
It happens for me too in ember 0.2.3 in linux

**Comment by hchood** [comment]
@adamsrog , I can confirm that I ran into this issue the first time I ran `ember new` after upgrading to 0.2.3.  Haven't seen it since (tried it a few more times).

```no-highlight
$ ember -v                                                                                                                                                                                                     
version: 0.2.3
node: 0.12.0
npm: 2.7.6
```

**Comment by sponomarev** [comment]
Have the same issue 
'''
version: 0.2.3
node: 0.12.2
npm: 2.7.6
'''

**Comment by esalinas00** [comment]
This happened once to me.

```
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```

**Comment by JKillian** [comment]
Same issue on my first attempt to create a new ember project:

    version: 0.2.3
    node: 0.10.25
    npm: 2.7.6

(I need to update node apparently!)

**Comment by knownasilya** [comment]
cc @calvinmetcalf this is the issue we saw today when setting up the new project.

**Comment by yoepus** [comment]
For what it is worth; I downloaded and installed latest ember today and had same issue. Deleted folder and rerun and no issue.

**Comment by christiannaths** [comment]
Same here. Exactly as @yoepus described. 
```
Yosemite 10.10.3
ember: 0.2.3
node: 0.12.2
npm: 2.7.5
```

**Comment by mjvezzani** [comment]
Downloaded ember-cli for first time on my machine. Attempted to build an app. Got the ENOENT package.json error. Found this issue, tried deleting the directory the app was in and tried again. Worked just fine.

**Comment by KurtRMueller** [comment]
Same here. First time fails, second times works like a charm.

**Comment by magnayn** [comment]
ditto

**Comment by vincentjr** [comment]
double ditto

**Comment by cimbriano** [comment]
Same. (Works first time, second time no problem.)

**Comment by mohrt** [comment]
Same here.

Yosemite: 10.10.3
ember: 0.2.3
node: 0.12.2
npm: 2.7.6

**Comment by stefanpenner** [comment]
I stumbled into this again. I believe this is actually related to upgrading NPM.

**Comment by artych** [comment]
Same on ember new. Message: Error: ENOENT, open '/ ... /package.json' at Error (native)
ember -v `version: 0.2.3 node: 0.12.0 npm: 2.7.6` Fails first time only.

**Comment by rwjblue** [comment]
@stefanpenner - Just had this happen on a co-workers machine.  It looks like there is a race condition when we change directories after generating a new app, and when the npm task runs.  So basically the npm task is trying to run before it is inside the new apps dir.

**Comment by stefanpenner** [comment]
@rwjblue ya, we can hard-code the prefix here: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-install.js#L19 but we don't always know it at this phase. When we have a `NullProject` we need to do additionally hacker to get the write `root`. I suspect the correct solution, will be to have `root` actually be more correct, likely by upgrading the NullProject's root, once we know it is a real project. Or adjusting that pattern, so if we are generating an app, we have the real project rather then  an NullProject.

**Comment by ianwdunlop** [comment]
Just discovered this issue on a new windows 7 machine. First time fails, second time it works.
version: 0.2.3 node: 0.12.2 npm: 2.7.6

**Comment by constantm** [comment]
Just had the same issue on OSX 10.10.3. First time fails - next attempt works.

```
➜ ember -v
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.12.1
npm: 2.7.6
```

**Comment by swr** [comment]
Same here. OSX 10.10.3. First time I received the error, next time works fine. Other attempts no error.

I had just updated both npm and ember-cli

```
ember -v
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```

**Comment by BransonGitomeh** [comment]
Same here.Fresh install Ubuntu 14.04.2

I had just installed the whole ember-cli,
````
ember -v
version: 0.2.4
node: 0.12.3
npm: 2.9.1
````

**Comment by xurde** [comment]
Looks totally a race-related thing. Tried once and got the error, deleted tried for a second time with absolutely no change and went fine.

**Comment by hjbolide** [comment]
Same, looks like a race condition, second time went through

**Comment by jacobroufa** [comment]
Just experienced the same thing on OSX 10.10.3.
```
$ ember -v
version: 0.2.5
node: 0.12.0
npm: 2.10.0
```

**Comment by visualjeff** [comment]
First time running ember new myProject with ember-cli 0.2.6 (docker image, debian, iojs 2.1.0) and received the following:

ember new myProject
...
ENOENT: no such file or directory, open '/root/package.json'
Error: ENOENT: no such file or directory, open '/root/package.json'
    at Error (native)

Second time running ember new myProject2 worked like a charm.

Just an FYI

**Comment by JasonBenn** [comment]
Just saw this after upgrading to 0.2.7, but only the first time.

**Comment by zeppelin** [comment]
Same as @JasonBenn

**Comment by adam-knights** [comment]
First time running ember-cli, version 0.2.7. On using new command I see version number twice and also get this error. Windows 7. Trying a second time works fine.

**Comment by mindaslab** [comment]
Okay, this is how I solved / did a  work around

My OS is Ubuntu 15.10 node version is 0.12.0 and npm is 2.8.4

```
$ ember new my-app
ENOENT, open '/home/ak/code/package.json'
Error: ENOENT, open '/home/ak/code/package.json'
    at Error (native)
```

And I went into my-app and did this

```
$ ember server
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ak/code/my-app/Brocfile.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

So still in my app folder I did the following

```
$ npm install
```
The above stuff will install npm packages 

```
$ ember server
```

Still it won't run, it will ask to install bower components, so do this

```
$ bower install
```

Now try this and it should work

```
$ ember server
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Livereload server on port 35729
Serving on http://localhost:4200/
```

**Comment by theazureshadow** [comment]
Agree that the error would be explained by a `chdir` race: it's trying to use `package.json` in the directory from which I ran `ember new`, rather than from the project directory. Running again succeeded.

```
csullins@Chriss-MacBook-Pro ~/tmp> ember new acceptance
version: 0.2.7
0.2.7
installing
  create .bowerrc
  ...
  create vendor/.gitkeep
ENOENT, open '/Users/csullins/tmp/package.json'
Error: ENOENT, open '/Users/csullins/tmp/package.json'
```

**Comment by searls** [comment]
Agree with @theazureshadow. I looked into this after experiencing it this morning and saw the same behavior. (on ember-cli@0.2.7, iojs@2.31, npm@2.11.3).

**Comment by ciel712** [comment]
Problem still exists. Tried doing Ember set-up the first time and encountered this issue. Ran it again and no problem.

**Comment by datfinesoul** [comment]
Had the same problem happen to me.  First time I ran it, got the `Error: ENOENT, open '/Users/phadviger/code/package.json'` error.  Deleted the project directory, ran it again, and it worked.

**Comment by jjhampton** [comment]
I too just suffered from this frightful error.  Deleted, re-ran and successfully installed.

**Comment by katgironpe** [comment]
I use OS X and get the same error.

**Comment by cllns** [comment]
+1 as well, on OS X

**Comment by theroseknight** [comment]
+1 happened just now, Ubuntu 14.04 (desktop), first ember new since upgrading ember CLI (been busy upgrading >_<), did not occur again on subsequent ember new commands.
