### ISSUE TITLE
Running ember-cli with ember@canary fails

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#3872]
I am following [the](http://discuss.emberjs.com/t/using-ember-cli-with-canary-build/4879) [guidelines](http://reefpoints.dockyard.com/2014/11/30/htmlbars_calling_all_testers.html) on running ember-cli with an ember canary build (is there an official or more up-to-date guideline?) This is failing with:

```
$ ember server --live-reload-port 35730 --port 4200
version: 0.2.3
Livereload server on port 35730
Serving on http://localhost:4200/
File: wfe-es6/templates/agents/-index.hbs
undefined is not a function
TypeError: undefined is not a function
    at Object.Ember.default.assert (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:132:26)
    at Object.Ember.default.deprecate (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:216:24)
    at /home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:9311:15
    at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12943:9)
    at visitors.ElementNode (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12959:18)
    at Walker.children (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12976:9)
    at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12944:14)
    at visitors.Program (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12953:18)
    at Walker.children (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12976:9)
    at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12944:14)
```

The same application is working fine with `ember@1.11.1`

I have taken care to:

```
npm cache clean
npm install
bower cache clean
bower update
```

I am running:

```
» ember -v
version: 0.2.3
node: 0.12.2
npm: 2.7.6
» bower -v
1.4.1
```

Any hints on what can be going wrong? Thanks!
-gonvaled

**Comment by rwjblue** [comment]
Working on this now.  Stay tuned....

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/10864 once merged.

**Comment by gonvaled** [comment]
Thanks, fixed for me!
