### ISSUE TITLE
HELP: ember generate component and ember generate route give errors

### ISSUE THREAD

**Issue by dimul** [ember-cli/ember-cli#6181]
### Explain
Project is written with coffeescript.
**ember-cli-coffeescript** addon is of latest version
Things started to happen after update from 2.5 to 2.7

In 2.5 everything works after update now I have this:

`ember g -h` and `ember generate route ...`
produce this error
`Cannot find module 'ember-cli/blueprints/route-addon'`

Running `ember generate component ...`
Produce this error
`Unknown blueprint: component`

ember-cli-legacy-blueprints do not help

#### Here is package.json

```
{
  "name": "project",
  "version": "0.0.42",
  "private": true,


  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "somerepo",
  "engines": {
    "node": ">= 0.10.0"
  },
  "dependencies": {
    "body-parser": "^1.13.2",
    "compression": "^1.5.1",
    "connect-restreamer": "^1.0.2",
    "express": "^4.13.1",
    "grunt-exec": "^1.0.0",
    "request": "^2.58.0"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "check-dependencies": "^0.12.0",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.7.0",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-coffeescript": "^1.13.2",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-document-title": "0.3.1",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^1.0.0-beta.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-stylus": "^1.0.5",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.7.0",
    "ember-export-application-global": "^1.0.5",
    "ember-i18n": "4.2.2",
    "ember-linkify": "2.5.1",
    "ember-load-initializers": "^0.5.1",
    "ember-radio-buttons": "^4.0.1",
    "ember-rapid-forms": "1.0.0-beta7",
    "ember-resolver": "^2.0.3",
    "ember-truth-helpers": "1.2.0",
    "ember-validations": "^2.0.0-alpha.4",
    "glob": "^7.0.5",
    "grunt": "~0.4.1",
    "grunt-aws": "^0.6.1",
    "grunt-cloudfront-clear": "0.0.1",
    "loader.js": "^4.0.1"
  }
}
```

#### Here is bower.json

```
{
  "name": "labrador",
  "dependencies": {
    "ember": "~2.7.0",
    "ember-cli-shims": "0.1.3",
    "ember-qunit-notifications": "0.1.0",
    "flexboxgrid": "~6.3.0",
    "moment": "~2.14.1",
    "c3": "0.4.11",
    "d3": "~3.5.17",
    "color-thief": "*",
    "fastclick": "~1.0.6",
    "typeahead.js": "~0.11.1",
    "numeral": "~1.5.3",
    "nib": "~1.1.0",
    "normalize.css": "~4.2.0",
    "pikaday-time": "owenmead/Pikaday#~1.3.3",
    "terraformer-wkt-parser": "~1.1.0",
    "terraformer": "~1.0.4",
    "jquery": "2.2.4",
    "marked": "^0.3.5"
  }
}
```
---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by nathanhammond** [comment]
This is not an Ember CLI issue. The blueprints you're looking for are provided by ember-cli-coffeescript and apparently that addon has not been updated to be compatible.

I cannot recommend that you use CoffeeScript in an Ember project as that is not a default supported path. You will continue to encounter issues like this which we won't attempt to solve. You'll have to take on the task of supporting this yourself.

I wish you the best of luck if you continue down this path! Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community if you get stuck.

/cc @kimroen
